/* GENERATED by wonka/bootcamp/glossary/build-portal.py . edit the source there, never this file */
(function () {
'use strict';
/* The Factory Dictionary: the words a student meets in the Wonka portal.
   ONE source for the glossary page (and later the portal view and the kit's
   guides/glossary.md). d = the day the word first shows up in the portal.
   [[Term]] or [[label|Term]] links to another entry.

   What belongs here (Jay, 24.9.2026): words that are Wonka's or Genrupt's, or
   that mean something specific in the bootcamp. Every student already sells on
   Amazon and uses Claude Code, so ASIN, SKU, main image, A+, Seller Central,
   Claude Code, sessions and slash commands stay out.
   Every definition: one or two short sentences, plain words, true to the kit. */
const GLOSSARY_DAYS = {
  1:  { room: 'The Front Gate',            accent: '#F5B841', mood: 'The gates part.' },
  2:  { room: 'Wonka, Meet My Product',    accent: '#8FCBE8', mood: 'The evidence comes in.' },
  3:  { room: 'The Creative Brief',        accent: '#D99A5B', mood: 'The plan is written.' },
  4:  { room: 'The Reference Room',        accent: '#FFE9B0', mood: 'The mold is cut, then proved.' },
  5:  { room: 'The Main Image Room',       accent: '#3ECFA3', mood: 'Many candidates, one hero.' },
  6:  { room: 'The Secondary Images Room', accent: '#6EC6E6', mood: 'The set fills with frames.' },
  7:  { room: 'The A+ Room',               accent: '#E0A94A', mood: 'The page takes shape.' },
  8:  { room: 'The Tasting Room',          accent: '#E0356B', mood: 'The tasters deliver their verdict.' },
  9:  { room: 'The Variations Room',       accent: '#B87333', mood: 'One good set. The rest of the family.' },
  10: { room: 'The Improvement Loop',      accent: '#F7D774', mood: 'The loop closes and turns again.' },
};

const GLOSSARY = [
  /* ---------- Day 1 . The Front Gate ---------- */
  { t: 'The machines', d: 1, a: ['machine', 'machines'],
    def: 'The two AI tools Wonka runs for you: [[Genrupt]] and [[OpenAI]]. When a better tool comes out, you swap the machine, not Wonka.' },
  { t: 'Genrupt', d: 1, a: ['listing builder', 'genrupt app'],
    def: 'An AI platform for Amazon sellers, and Wonka\'s main machine. It does your market research, reference sheets, listing images, A+ and variations. In its app you compare images and pick.' },
  { t: 'OpenAI', d: 1, a: ['api credit', 'platform.openai.com', 'chatgpt', 'gpt-image'],
    def: 'The second machine. Wonka uses it for cheaper image drafts, quick edits and the [[Tasting Room]]. It runs on API credit, separate from any ChatGPT subscription.' },
  { t: 'MCP', d: 1, a: ['connector', 'custom connector'],
    def: 'The connection between Claude and Genrupt. Wonka places the order, Genrupt is the kitchen, and MCP carries it back and forth.' },
  { t: 'API key', d: 1, a: ['openai key', 'secret key', 'key'],
    def: 'The private key that lets Wonka use OpenAI directly and bills the usage to your API account. It lives in your [[.env file]], never in the chat.' },
  { t: '.env file', d: 1, a: ['env', 'dotenv'],
    def: 'A private file in your Wonka folder that holds your OpenAI [[API key]]. The key goes in this file, never into the chat.' },
  { t: 'Credits', d: 1, a: ['credit', 'credit balance'],
    def: 'Genrupt\'s currency. Research, reference sheets, images and A+ all cost credits, and Wonka tells you the cost.' },
  { t: 'Spending rules', d: 1, a: ['cost', 'budget', 'spending limit', 'cap', 'price', 'money', 'spend'],
    def: 'Wonka never spends silently. Once you approve the brief, planned runs and [[routine fixes|Routine fixes]] go ahead and he reports each cost. Big spends, like a [[Draft Blast]], need your yes.' },
  { t: '/machines-check', d: 1, a: ['machines check', 'pass', 'health check'],
    def: 'Wonka\'s health check for Python, Genrupt and OpenAI. You\'re set when all three say PASS. Run it first whenever something stops working.' },
  { t: 'Python', d: 1,
    def: 'A free program some of Wonka\'s tools run on. Nothing to buy or learn; the machines check makes sure it\'s there.' },
  { t: 'First Candy', d: 1, a: ['welcome card', 'first image'],
    def: 'A tiny test image on Day 1. It costs a few cents and proves the OpenAI connection works end to end.' },
  { t: 'factory/ and output/', d: 1, a: ['factory', 'output', 'factory folder', 'output folder', 'products folder', 'product room'],
    def: 'Two folders inside Wonka. factory/ is his workshop, with a room (a folder) for each product. output/ holds finished files, from the First Candy to your final upload package.' },

  /* ---------- Day 2 . Wonka, Meet My Product ---------- */
  { t: 'Reference photos', d: 2, a: ['photos', 'product photos', 'shot list'],
    def: 'Your own unedited photos of the real product, from every useful angle. They are the strongest product evidence. No product in hand? See the [[customer-photo fallback|Customer-photo fallback]].' },
  { t: 'Customer-photo fallback', d: 2, a: ['fallback', 'customer photos', 'no product', 'review photos'],
    def: 'No product in hand? Wonka can use customer-review photos plus the live listing gallery as an approved fallback. They are weaker than your own, so he records their source.' },
  { t: 'Preflight card', d: 2, a: ['preflight', 'niche'],
    def: 'The summary Wonka shows before any paid research: your product, the niche and the cost. Check that the niche is exactly yours, then approve.' },
  { t: 'Genrupt extension', d: 2, a: ['chrome extension', 'extension', 'reviews'],
    def: 'A Chrome add-on that lets Genrupt read Amazon reviews for your research. Install it, pin it and sign in on Amazon before Day 2.' },
  { t: 'Product Report', d: 2, cmd: '/meet-my-product', a: ['research', 'product-report.md', 'meet my product', 'report'],
    def: 'Wonka\'s Day 2 research on your market: what buyers expect, what they complain about and where your listing loses them. The brief is built on it.' },
  { t: 'Must-Haves', d: 2, a: ['must haves'],
    def: 'What shoppers expect from any product in your category.' },
  { t: 'Expectation gap', d: 2,
    def: 'Where your images promise something your reviews complain about.' },
  { t: 'Whitespace', d: 2, a: ['white space'],
    def: 'A buyer need that competitors are not explaining well. A place where your images can stand out.' },
  { t: 'Funnel diagnosis', d: 2, a: ['funnel', 'ctr', 'cvr', 'click problem', 'convince problem', 'traffic problem'],
    def: 'Wonka\'s read of where you most likely lose buyers: they don\'t find you (traffic), don\'t click (main image) or don\'t buy (gallery and A+). It points where the effort goes.' },
  { t: 'Selling point', d: 2, a: ['sp1', 'selling points', 'selling-points.md', 'coverage map'],
    def: 'One reason to buy. Each gets an ID like SP1, so the brief can show where every point appears, or why it was left out.' },
  { t: 'Best frame', d: 2, a: ['competitor', 'competitors', 'competitors.md'],
    def: 'The one competitor image that sets the bar. Not to copy. To beat.' },
  { t: 'Gallery Sheets', d: 2, a: ['gallery sheet', 'competitor galleries'],
    def: 'Your current gallery and your competitors\' galleries, each shown on one image, so you can compare whole galleries at a glance.' },
  { t: '“estimated”', d: 2, a: ['estimated', 'estimate', 'guess', 'source label', 'real data'],
    def: 'The label for something Wonka worked out from the evidence, not confirmed by your own data. He keeps estimates apart from facts.' },
  { t: 'Waiver', d: 2, a: ['waive', 'skip', 'missing'],
    def: 'Telling Wonka to go on without something he asked for, by name: “I have no critical reviews, proceed without them.” A generic “just go” doesn\'t count.' },
  { t: 'Improvement Log', d: 2, a: ['improvement log.md', 'lessons', 'memory'],
    def: 'Wonka\'s notebook of lessons from your products: what worked, what failed, what you prefer. Empty on your first product, fuller with every one after.' },
  { t: 'Prepare me for compact', d: 2, say: 'Prepare me for compact.', a: ['compact', '/compact', 'context', 'context meter', 'chat is full'],
    def: 'Say this when the chat fills up (about 25% of the context meter left). Wonka saves the work and gives you a /compact command to paste, then carries on.' },

  /* ---------- Day 3 . The Creative Brief ---------- */
  { t: 'Creative brief', d: 3, cmd: '/creative-brief', a: ['brief', 'creative-brief.md', 'plan'],
    def: 'The plan for your whole image set: which buyer question each image answers, what it says and what it must never promise. Nothing is made until you approve it.' },
  { t: 'owner-review.md', d: 3, a: ['decision page', 'owner review'],
    def: 'The short decision page from the brief, written for you. Read this one carefully and approve it; the full brief is Wonka\'s working file.' },
  { t: 'Slot', d: 3, a: ['slots', 'slot 1'],
    def: 'One image position in your listing. Slot 1 is the main image. Each slot has one job: one buyer question, one message.' },
  { t: 'Main-image tactics', d: 3, a: ['tactics', 'hang_tag', 'human_contact', 'packaging_expansion', 'genrupt_choice', 'mix and match'],
    def: 'Four ways to make the main image stand out: a [[hang tag|Hang tag]], a hand touching or holding the product, expanded packaging, or Genrupt\'s own direction. You can use several.' },
  { t: 'Hang tag', d: 3, a: ['tag', 'hang-tag'],
    def: 'A small tag hanging from the product in the main image, with a short message: up to 28 characters and 5 words.' },
  { t: 'Claims check', d: 3, a: ['promise check', 'claim', 'claims'],
    def: 'Wonka checks every promise in the brief against the research. Anything you can\'t back up gets softened or cut. In the file it\'s called Promise check.' },
  { t: 'Planner', d: 3, a: ['genrupt planner', 'saved plan', 'send'],
    def: 'Genrupt\'s planning step, read as a second opinion. If it caught something useful the brief missed, Wonka shows you and you decide. The approved brief stays in charge.' },
  { t: 'Read-back', d: 3, a: ['read back', 'reads back'],
    def: 'Wonka reads what was actually saved in Genrupt, like your plan or your picks, and shows it to you. That\'s how a bad save gets caught early.' },
  { t: 'Approve in words', d: 3, a: ['approve', 'approval', 'the brief is approved'],
    def: 'Wonka moves on only when you say it clearly, like “The brief is approved.” “Looks good” or silence isn\'t a yes.' },
  { t: 'Gate', d: 3, a: ['the gate', 'blocked', 'refuses'],
    def: 'What must be true before the next day can start. Example: Day 5 won\'t make images until Day 4 ends with PASS and LOCKED.' },

  /* ---------- Day 4 . The Reference Room ---------- */
  { t: 'Reference Sheet', d: 4, cmd: '/reference-sheet', a: ['sheet', 'sheets', 'reference', 'identity sheet', 'mold'],
    def: 'An image, not a document. Genrupt builds it from your photos to show the product\'s angles, details, size and materials. Every later image copies the product from it.' },
  { t: 'Panel', d: 4, a: ['panels', 'panel by panel'],
    def: 'One small picture inside a reference sheet. Check each one on its own: one can be wrong while the rest are right.' },
  { t: 'Scale cue', d: 4, a: ['scale', 'size'],
    def: 'A hand or an everyday object in the picture that shows your product\'s real size. Numbers alone don\'t always stop the AI from shrinking or stretching it.' },
  { t: 'Smoke Test', d: 4, a: ['smoke'],
    def: 'One cheap image per slot that answers two questions: is this my product, and is this the brief I wanted? These are tests, not your final images.' },
  { t: 'Approved vs locked', d: 4, a: ['locked', 'lock', 'approved', 'reference status'],
    def: 'Approved means you signed off on the reference sheets. Locked means they also passed the [[smoke test|Smoke Test]]. Day 5 needs LOCKED.' },
  { t: 'Brand kit', d: 4, cmd: '/brand-kit', a: ['branding', 'branding preset', 'preset', 'brand book', 'style guide'],
    def: 'Optional. From your real Brand Book or Style Guide, Wonka saves colors, typography and tone as a Genrupt branding preset. No guide? Go unbranded, or ask him to propose a direction.' },
  { t: 'Blast', d: 4, a: ['blasts'],
    def: 'One Genrupt run that makes many images at once. You\'ll meet the [[Draft Blast]] on Day 5 and the [[Theme Blast]] on Day 6.' },

  /* ---------- Day 5 . The Main Image Room ---------- */
  { t: 'Draft Blast', d: 5, cmd: '/main-image', a: ['drafts', 'draft'],
    def: 'Genrupt\'s big batch of main-image options. You browse them in the Genrupt app and send the ones you like to [[Refine]].' },
  { t: 'Contact sheet', d: 5, a: ['numbered sheet', 'overview', 'numbered overview'],
    def: 'One image with many small numbered pictures on it, so you can see a whole set at a glance and pick by number.' },
  { t: 'Pool', d: 5, a: ['openai pool', 'collection'],
    def: 'The OpenAI side of the main-image run: a numbered set of drafts saved on your computer.' },
  { t: 'Shortlist', d: 5, a: ['short list', 'candidates'],
    def: 'The images you like from both machines, together on one numbered sheet, so you and Wonka talk about the same picture.' },
  { t: 'Refine', d: 5, a: ['send to refine', 'refine tab'],
    def: 'Genrupt\'s tab for comparing versions and choosing. Send to Refine moves your picks there; it doesn\'t make new images.' },
  { t: 'Listing Preview', d: 5, a: ['preview', 'compare', 'search results'],
    def: 'A Genrupt view that shows your image beside competitors, on desktop and on a phone. Use it before you pick.' },
  { t: '/inspect', d: 5, a: ['inspect', 'inspection', 'quality check'],
    def: 'Wonka\'s quality check. He looks at the product, the text and how each image reads when small, fixes the clear problems, then scores and ranks the set.' },
  { t: 'Scorecard', d: 5, a: ['scorecards', 'score', 'ranking'],
    def: 'The report /inspect writes: a card per image with its scores, a ranking and the [[compliance gate|Compliance gate]] result.' },
  { t: 'Compliance gate', d: 5, a: ['compliance'],
    def: 'The pass-or-fail part of /inspect. It catches what must never be on an image, like fake badges, made-up numbers or star ratings.' },
  { t: '/fix', d: 5, a: ['fix', 'fixing room', 'repair'],
    def: 'Fixes a problem in an image. Wonka finds it, or you describe it in plain words. You never need to edit an image yourself.' },
  { t: 'Routine fixes', d: 5, a: ['routine fix', 'routine edits', 'small fixes'],
    def: 'Small image fixes that cost cents. Wonka runs them without asking and tells you what he changed. Bigger or repeated rounds wait for your yes.' },
  { t: 'Edit vs regenerate', d: 5, a: ['edit', 'regenerate', 'rerun'],
    def: 'Edit changes one part and keeps the rest. Regenerate makes a new image from scratch. Small problem: edit. Wrong idea: regenerate. Wonka picks.' },
  { t: 'Primary, alternatives, backup', d: 5, a: ['primary', 'alternative', 'alternatives', 'backup', 'winner', 'product-on-white'],
    def: 'Your main-image picks. Primary: the one you\'ll use. Alternatives: other strong ones to test later. Backup: a plain product-on-white, the safe option.' },
  { t: 'Upscale', d: 5, a: ['upscaling', 'resolution'],
    def: 'Enlarges a finished image that is smaller than your listing needs. Do it after the edits are settled, then check small text, logos and markings again.' },
  { t: 'status.md', d: 5, a: ['status'],
    def: 'Wonka\'s record of where your product stands: what\'s approved, what\'s locked and which images you picked.' },

  /* ---------- Day 6 . The Secondary Images Room ---------- */
  { t: 'Theme Blast', d: 6, cmd: '/secondary-images', a: ['listing theme', 'design directions', 'rows'],
    def: 'A Genrupt run that shows your secondary images in several design styles, one style per row, so you can compare looks and pick one.' },
  { t: 'Style Reference', d: 6, a: ['shirt icon', 'style label', 'lock row style', 'style'],
    def: 'The one image whose look your whole gallery follows. Click the shirt icon on it in Genrupt; it gets a purple Style label.' },
  { t: 'Green check', d: 6, a: ['checkmark', 'green border', 'chosen'],
    def: 'In Genrupt\'s Refine tab, the checkmark saves your pick for a slot and gives it a green border. Green means chosen, not checked for quality.' },
  { t: 'Generation blocked', d: 6, a: ['blocked slot', 'complete', 'reopen'],
    def: 'A Genrupt mark on a slot: no new images get made there. It isn\'t an approval or a pick. Ask Wonka to reopen the slot if you want more.' },

  /* ---------- Day 7 . The A+ Room ---------- */
  { t: 'Concept', d: 7, cmd: '/aplus', a: ['concepts', 'a+', 'aplus', 'display modes', 'mode', 'desktop', 'mobile'],
    def: 'One complete A+ page design. You choose how many Wonka makes, compare the whole pages, and pick one for each mode (desktop, mobile).' },
  { t: 'Export', d: 7, a: ['exported', 'module files', 'modules'],
    def: 'Your chosen A+ page, saved as numbered module files. Later fixes are made on these files, and a fresh export from Genrupt won\'t include them.' },
  { t: '/fix-faces', d: 7, a: ['fix faces', 'face', 'faces'],
    def: 'Targets an AI-looking face for a more natural result while protecting the product, text, pose and layout. Check the face and the area around it afterward.' },

  /* ---------- Day 8 . The Tasting Room ---------- */
  { t: 'Tasting Room', d: 8, cmd: '/tasting-room', a: ['tasting round', 'ai shoppers', 'tasters'],
    def: 'About 100 AI tasters, built around your buyer profile, compare your images with a [[benchmark|Benchmark]] and explain what they\'d choose and why. Directional insight, not real shopper or sales data.' },
  { t: 'Benchmark', d: 8, a: ['compared against'],
    def: 'What your images are compared against: your current live listing, or a strong competitor if you\'re not live yet.' },
  { t: 'Incumbent', d: 8, a: ['live image', 'live gallery', 'current listing', 'live listing'],
    def: 'The image or gallery live on your Amazon listing right now. In the Tasting Room it is the real-world control your new work has to beat.' },
  { t: 'Tasting Card', d: 8, a: ['tasting cards', 'card'],
    def: 'The Tasting Room\'s report: what the panel preferred, how strong the signal was, and the objections and reasons behind the picks.' },
  { t: 'Clear lead, Lean, Toss-up', d: 8, a: ['clear lead', 'lean', 'toss-up', 'tossup', 'verdict'],
    def: 'How firm a Tasting Card result is. Clear lead: safe to act on. Lean: a hint, you decide. Toss-up: a tie, so read the comments and ignore the numbers.' },

  /* ---------- Day 9 . The Variations Room ---------- */
  { t: '/variations', d: 9, a: ['variations', 'variation', 'variant', 'colors', 'sizes', 'family'],
    def: 'Adapts your approved images to your product\'s other versions, like different colors, sizes or scents. Wonka shows you the first images to check before he makes the rest.' },

  /* ---------- Day 10 . The Improvement Loop ---------- */
  { t: '/ready-to-upload', d: 10, a: ['ready to upload', 'package', 'upload', 'final files'],
    def: 'Packs your final files into one folder, output/[product-name]-package, with an upload list. Check the files, then upload them to Amazon.' },
  { t: 'Improvement Loop', d: 10, cmd: '/improvement-loop', a: ['lessons learned'],
    def: 'Wonka writes what this product taught him into the [[Improvement Log]]: what won, what you prefer, what to do better. Your next product starts from there.' },
  { t: '/factory-report', d: 10, a: ['factory report', 'status report'],
    def: 'A free status report on all your products: where each one stands and the next step for each.' },
];

/* Every command in the kit, in the order the bootcamp uses them. */
const GLOSSARY_COMMANDS = [
  { c: '/machines-check',   d: 1,  def: 'Checks that Python, Genrupt and OpenAI work. Run it first when something breaks.' },
  { c: '/meet-my-product',  d: 2,  def: 'Brings a product into the factory, researches it and writes the Product Report.' },
  { c: '/creative-brief',   d: 3,  def: 'Turns the research into a plan for every image, then saves it in Genrupt once you approve.' },
  { c: '/reference-sheet',  d: 4,  def: 'Builds reference sheets from your photos. Once you approve them, it runs the smoke test.' },
  { c: '/brand-kit',        d: 4,  def: 'Optional. Saves your brand\'s colors, fonts and tone from your brand book, or proposes a direction if you ask.' },
  { c: '/main-image',       d: 5,  def: 'Makes main-image options on both machines at once.' },
  { c: '/inspect',          d: 5,  def: 'Checks images for mistakes, fixes the clear ones and scores the set.' },
  { c: '/fix',              d: 5,  def: 'Fixes a problem you or Wonka found in an image.' },
  { c: '/secondary-images', d: 6,  def: 'Makes the rest of your gallery in one style.' },
  { c: '/aplus',            d: 7,  def: 'Makes A+ page designs for the modes you choose, then exports the pages you pick.' },
  { c: '/fix-faces',        d: 7,  def: 'Makes AI-looking people look real, and touches nothing else.' },
  { c: '/tasting-room',     d: 8,  def: 'Runs the AI shopper panel on your images.' },
  { c: '/variations',       d: 9,  def: 'Adapts your images to your product\'s other colors, sizes or scents.' },
  { c: '/ready-to-upload',  d: 10, def: 'Packs your final files for Amazon.' },
  { c: '/improvement-loop', d: 10, def: 'Saves what this product taught Wonka, for the next one.' },
  { c: '/factory-report',   d: 10, def: 'Shows where every product stands and what comes next.' },
];

/* ============================================================
   THE FACTORY DICTIONARY . portal module (render + behaviour)
   build-portal.py wraps terms.js + this file into ONE closure and writes
   jaygptpro.com/wonka-bootcamp/dictionary.js. Edit terms.js for words,
   this file for behaviour; never edit the built dictionary.js by hand.
   Exposes one global, window.WonkaDictionary: { mount, open, count }.
   Every class and id is prefixed fd- so nothing collides with the portal.
   ============================================================ */
var FD = { mounted: false, el: null, opts: null, mode: 'day' };

function fdSlug(s) {
  return String(s).toLowerCase().replace(/^[\/.“"]+/, '').replace(/\+/g, ' plus').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}
function fdEsc(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}
function fdNorm(s) { return String(s).toLowerCase().replace(/[^a-z0-9+]+/g, ' ').trim(); }
function fdSortKey(t) { return t.replace(/^[\/."“]+/, '').toLowerCase(); }
function fdAcc(d) { return (GLOSSARY_DAYS[d] || {}).accent || '#B87333'; }

var FD_BY_TITLE = {};
GLOSSARY.forEach(function (g) {
  g.id = fdSlug(g.t);
  FD_BY_TITLE[g.t.toLowerCase()] = g;
  g.hay = fdNorm([g.t].concat(g.a || [], g.cmd || '', g.say || '').join(' '));
  g.hayDef = fdNorm(g.def);
});
var FD_DAY_ORDER = Object.keys(GLOSSARY_DAYS).map(Number).sort(function (a, b) { return a - b; });

function fdCodeify(html) {
  return html
    .replace(/(^|[\s(])(\/[a-z][a-z-]+)(?=[\s.,;:)]|$)/g, '$1<code>$2</code>')
    .replace(/(output\/\[product-name\]-package|factory\/|output\/)/g, '<code>$1</code>')
    .replace(/\b([a-z-]+\.md)\b/g, '<code>$1</code>');
}
function fdDef(text) {
  var parts = [], re = /\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g, last = 0, m;
  while ((m = re.exec(text))) {
    parts.push(fdCodeify(fdEsc(text.slice(last, m.index))));
    var target = FD_BY_TITLE[(m[2] || m[1]).toLowerCase()];
    parts.push(target ? '<a class="fd-xref" href="#dictionary-' + target.id + '" data-fd-to="' + target.id + '">' + fdEsc(m[1]) + '</a>' : fdEsc(m[1]));
    last = re.lastIndex;
  }
  parts.push(fdCodeify(fdEsc(text.slice(last))));
  return parts.join('');
}

var FD_LINK_SVG = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M10 13a5 5 0 0 0 7.1 0l3-3a5 5 0 0 0-7.1-7.1l-1.7 1.7"/><path d="M14 11a5 5 0 0 0-7.1 0l-3 3a5 5 0 0 0 7.1 7.1l1.7-1.7"/></svg>';
var FD_WA = 'https://wa.me/972535576816?text=';
function fdWa(word) { return FD_WA + encodeURIComponent("Hi Jay, I'm part of the Wonka Bootcamp. A word for the Factory Dictionary: " + (word || '')); }

function fdTag(d) { return '<span class="fd-tag"><i></i>Day ' + d + '</span>'; }
function fdEntry(g, showTag) {
  var extra = g.cmd ? '<div class="fd-cmd">Run <code>' + fdEsc(g.cmd) + '</code></div>'
    : g.say ? '<div class="fd-cmd">Say <code>' + fdEsc(g.say) + '</code></div>' : '';
  var mono = g.t.charAt(0) === '/';
  return '<article class="fd-entry" id="fd-t-' + g.id + '" style="--fd-e:' + fdAcc(g.d) + '">' +
    '<h3 class="fd-term' + (mono ? ' fd-mono' : '') + '"><span class="fd-t">' + fdEsc(g.t) + '</span>' + (showTag ? '<br>' + fdTag(g.d) : '') + '</h3>' +
    '<div class="fd-body"><p class="fd-def">' + fdDef(g.def) + '</p>' + extra + '</div>' +
    '<button class="fd-link" type="button" data-fd-copy="' + g.id + '" aria-label="Copy a link to ' + fdEsc(g.t) + '" title="Copy link">' + FD_LINK_SVG + '</button>' +
    '</article>';
}
function fdCommand(c) {
  return '<article class="fd-entry" style="--fd-e:' + fdAcc(c.d) + '">' +
    '<h3 class="fd-term fd-mono"><span class="fd-t">' + fdEsc(c.c) + '</span><br>' + fdTag(c.d) + '</h3>' +
    '<div class="fd-body"><p class="fd-def">' + fdEsc(c.def) + '</p></div><span></span></article>';
}
function fdDayGroup(d, items) {
  var info = GLOSSARY_DAYS[d], base = FD.opts.assetBase;
  return '<section class="fd-group fd-has-art" id="fd-day-' + d + '" style="--fd-acc:' + info.accent + '">' +
    '<header class="fd-ghead">' +
      '<img class="fd-art" src="' + base + 'room-' + d + '.webp" alt="" loading="lazy" decoding="async">' +
      '<div class="fd-gtext"><div class="fd-geyebrow">Day ' + d + '</div><h2>' + fdEsc(info.room) + '</h2>' +
        '<p class="fd-gmood">' + fdEsc(info.mood) + '</p></div>' +
      '<span class="fd-gcount">' + items.length + (items.length === 1 ? ' word' : ' words') + '</span>' +
    '</header>' +
    '<div class="fd-entries">' + items.map(function (g) { return fdEntry(g, false); }).join('') + '</div>' +
    '</section>';
}
function fdPlainGroup(id, title, eyebrow, inner) {
  return '<section class="fd-group fd-plain" id="' + id + '"><header class="fd-ghead fd-lhead"><div class="fd-gtext">' +
    (eyebrow ? '<div class="fd-geyebrow">' + eyebrow + '</div>' : '') + '<h2>' + title + '</h2></div></header>' +
    '<div class="fd-entries">' + inner + '</div></section>';
}

function fd$(sel) { return FD.el.querySelector(sel); }
function fdHeaderH() { return (FD.opts.headerHeight && FD.opts.headerHeight()) || 0; }

function fdRender() {
  var q = fd$('.fd-q').value, list = fd$('.fd-list'), jump = fd$('.fd-jump'), status = fd$('.fd-status');
  FD.el.classList.toggle('fd-has-q', !!q.trim());
  if (q.trim()) {
    var words = fdNorm(q).split(' ').filter(Boolean), joined = words.join(' '), hits = [];
    GLOSSARY.forEach(function (g) {
      var inHay = words.every(function (w) { return g.hay.indexOf(w) !== -1; });
      var inAll = inHay || words.every(function (w) { return (g.hay + ' ' + g.hayDef).indexOf(w) !== -1; });
      if (!inAll) return;
      var names = [fdNorm(g.t)].concat((g.a || []).map(fdNorm), g.cmd ? [fdNorm(g.cmd)] : []);
      var score = names.indexOf(joined) !== -1 ? 0 : names.some(function (n) { return n.indexOf(joined) === 0; }) ? 1 : inHay ? 2 : 3;
      hits.push({ g: g, s: score });
    });
    hits.sort(function (a, b) { return a.s - b.s || fdSortKey(a.g.t).localeCompare(fdSortKey(b.g.t)); });
    if (!hits.length) {
      list.innerHTML = '<div class="fd-empty"><p class="fd-big">No word matches “' + fdEsc(q.trim()) + '”.</p>' +
        '<p>Try a shorter word, or <a class="fd-xref" href="' + fdWa(q.trim()) + '" target="_blank" rel="noopener">send it to Jay</a> and he’ll add it.</p></div>';
      status.textContent = 'No matches';
    } else {
      list.innerHTML = '<div class="fd-results">' + hits.map(function (h) { return fdEntry(h.g, true); }).join('') + '</div>';
      status.innerHTML = '<b>' + hits.length + '</b> ' + (hits.length === 1 ? 'word' : 'words') + ' for “' + fdEsc(q.trim()) + '”';
      fdHighlight(list, words);
    }
  } else if (FD.mode === 'az') {
    var sorted = GLOSSARY.slice().sort(function (a, b) { return fdSortKey(a.t).localeCompare(fdSortKey(b.t)); });
    var groups = {}, order = [];
    sorted.forEach(function (g) {
      var L = fdSortKey(g.t).charAt(0).toUpperCase();
      if (!groups[L]) { groups[L] = []; order.push(L); }
      groups[L].push(g);
    });
    list.innerHTML = order.map(function (L) {
      return fdPlainGroup('fd-letter-' + L, L, '', groups[L].map(function (g) { return fdEntry(g, true); }).join(''));
    }).join('');
    jump.innerHTML = order.map(function (L) {
      return '<a class="fd-chip" href="#dictionary" data-fd-group="fd-letter-' + L + '">' + L + '</a>';
    }).join('');
  } else if (FD.mode === 'cmd') {
    list.innerHTML = fdPlainGroup('fd-commands', 'Every command', 'In the order you use them', GLOSSARY_COMMANDS.map(fdCommand).join(''));
    jump.innerHTML = '';
  } else {
    var html = '', chips = '<span class="fd-chip fd-label" aria-hidden="true">Day</span>';
    FD_DAY_ORDER.forEach(function (d) {
      var items = GLOSSARY.filter(function (g) { return g.d === d; });
      if (!items.length) return;
      html += fdDayGroup(d, items);
      chips += '<a class="fd-chip" href="#dictionary-day-' + d + '" data-fd-group="fd-day-' + d + '" style="--fd-acc:' + fdAcc(d) + '" title="Day ' + d + ' · ' + fdEsc(GLOSSARY_DAYS[d].room) + '">' + d + '</a>';
    });
    list.innerHTML = html;
    jump.innerHTML = chips;
  }
  fdMeasure();
  fdObserve();
}

function fdHighlight(root, words) {
  var re = new RegExp('(' + words.map(function (w) { return w.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }).join('|') + ')', 'gi');
  root.querySelectorAll('.fd-t, .fd-def').forEach(function (el) {
    var walker = document.createTreeWalker(el, NodeFilter.SHOW_TEXT), nodes = [], n;
    while ((n = walker.nextNode())) nodes.push(n);
    nodes.forEach(function (node) {
      re.lastIndex = 0;
      if (!re.test(node.nodeValue)) return;
      re.lastIndex = 0;
      var span = document.createElement('span');
      span.innerHTML = fdEsc(node.nodeValue).replace(re, '<mark>$1</mark>');
      node.parentNode.replaceChild(span, node);
    });
  });
}

/* sticky toolbar sits under the portal header; anchors land under both */
function fdMeasure() {
  var tb = fd$('.fd-toolbar');
  FD.top = fdHeaderH() + 10;
  FD.el.style.setProperty('--fd-top', FD.top + 'px');
  FD.el.style.setProperty('--fd-tb', tb.offsetHeight + 'px');
}
function fdStuck() {
  if (!FD.el || !FD.el.offsetParent) return;
  // the portal header changes height (its day rail wraps to a second row on a phone,
  // after mount): re-read it here, or the bar sticks UNDER the header (measured 26px, 24.9)
  var top = fdHeaderH() + 10;
  if (top !== FD.top) { FD.top = top; FD.el.style.setProperty('--fd-top', top + 'px'); }
  var tb = fd$('.fd-toolbar'), seg = fd$('.fd-seg');
  var was = tb.classList.contains('fd-stuck');
  if (!was) FD.el.style.setProperty('--fd-seg-h', (seg.offsetHeight + 10) + 'px');
  var now = tb.getBoundingClientRect().top <= fdHeaderH() + 10.5;
  if (now !== was) { tb.classList.toggle('fd-stuck', now); fdMeasure(); }
}
var fdIO;
function fdObserve() {
  if (fdIO) fdIO.disconnect();
  if (!('IntersectionObserver' in window)) return;
  var chips = FD.el.querySelectorAll('[data-fd-group]');
  if (!chips.length) return;
  var jump = fd$('.fd-jump'), tb = fd$('.fd-toolbar');
  fdIO = new IntersectionObserver(function (entries) {
    entries.forEach(function (e) {
      if (!e.isIntersecting) return;
      chips.forEach(function (c) { c.setAttribute('aria-current', c.dataset.fdGroup === e.target.id ? 'true' : 'false'); });
      var active = jump.querySelector('[aria-current="true"]');
      if (active) {
        var jr = jump.getBoundingClientRect(), ar = active.getBoundingClientRect();
        if (ar.left < jr.left || ar.right > jr.right) jump.scrollLeft += (ar.left - jr.left) - jr.width / 2 + ar.width / 2;
      }
    });
  }, { rootMargin: '-' + (fdHeaderH() + tb.offsetHeight + 30) + 'px 0px -60% 0px' });
  FD.el.querySelectorAll('.fd-group').forEach(function (s) { fdIO.observe(s); });
}
function fdGoTo(domId, flash, hash) {
  var el = document.getElementById(domId);
  if (!el) return false;
  var tb = fd$('.fd-toolbar');
  var y = el.getBoundingClientRect().top + window.scrollY - (fdHeaderH() + tb.offsetHeight + 24);
  window.scrollTo({ top: Math.max(0, y), behavior: 'instant' });
  // second pass: the jump may have stuck the bar (and on a phone folded it), so land again
  fdStuck();
  var off = el.getBoundingClientRect().top - (fdHeaderH() + tb.offsetHeight + 24);
  if (Math.abs(off) > 2) window.scrollBy({ top: off, behavior: 'instant' });
  if (flash) { el.classList.remove('fd-flash'); void el.offsetWidth; el.classList.add('fd-flash'); }
  if (hash) { try { history.replaceState(null, '', location.pathname + location.search + '#dictionary-' + hash); } catch (e) {} }
  return true;
}
function fdSetMode(m) {
  FD.mode = m;
  FD.el.querySelectorAll('.fd-seg button').forEach(function (x) { x.setAttribute('aria-pressed', x.dataset.fdMode === m ? 'true' : 'false'); });
}

function fdCopy(text) {
  var ok = false;
  try {
    var ta = document.createElement('textarea');
    ta.value = text; ta.setAttribute('readonly', ''); ta.style.position = 'fixed'; ta.style.opacity = '0';
    document.body.appendChild(ta); ta.select(); ok = document.execCommand('copy'); document.body.removeChild(ta);
  } catch (e) { ok = false; }
  if (!ok && navigator.clipboard) { navigator.clipboard.writeText(text).catch(function () {}); ok = true; }
  return ok;
}

function fdMount(el, opts) {
  if (FD.mounted) return;
  FD.el = el; FD.opts = opts || {}; FD.mounted = true;
  var base = FD.opts.assetBase || '';
  el.innerHTML =
    '<div class="fd">' +
    '<header class="fd-hero" style="--fd-banner:url(\'' + base + 'banner.webp\')">' +
      '<div class="fd-hero-in">' +
        '<button type="button" class="fd-back" data-fd-back><span aria-hidden="true">&larr;</span> <span class="fd-back-t">Back</span></button>' +
        '<p class="fd-eyebrow">Glossary</p>' +
        '<h1>The Factory <em>Dictionary</em></h1>' +
        '<p class="fd-sub">Short answers to the bootcamp’s own words. Grouped by the day you first meet them.</p>' +
        '<div class="fd-bulbs" aria-hidden="true"></div>' +
      '</div>' +
    '</header>' +
    '<div class="fd-wrap">' +
      '<div class="fd-toolbar">' +
        '<div class="fd-row">' +
          '<div class="fd-search">' +
            '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.6-3.6"/></svg>' +
            '<label for="fd-q" class="sr-only">Search the dictionary</label>' +
            '<input id="fd-q" class="fd-q" type="search" placeholder="Search a word, like smoke test" autocomplete="off" spellcheck="false">' +
            '<button class="fd-clear" type="button" aria-label="Clear search">×</button>' +
          '</div>' +
          '<div class="fd-seg" role="group" aria-label="How to list the words">' +
            '<button type="button" data-fd-mode="day" aria-pressed="true">By day</button>' +
            '<button type="button" data-fd-mode="az" aria-pressed="false">A to Z</button>' +
            '<button type="button" data-fd-mode="cmd" aria-pressed="false">Commands</button>' +
          '</div>' +
        '</div>' +
        '<nav class="fd-jump" aria-label="Jump to"></nav>' +
        '<p class="fd-status" aria-live="polite"></p>' +
      '</div>' +
      '<div class="fd-list"></div>' +
      '<footer class="fd-foot">' +
        '<p class="fd-big">Missing a word?</p>' +
        '<p>Send it to Jay and he’ll add it.</p>' +
        '<a class="fd-wa" target="_blank" rel="noopener" href="' + fdWa('') + '">' +
          '<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 2a10 10 0 0 0-8.6 15.1L2 22l5-1.3A10 10 0 1 0 12 2Zm0 18.2a8.2 8.2 0 0 1-4.2-1.2l-.3-.2-3 .8.8-2.9-.2-.3A8.2 8.2 0 1 1 12 20.2Zm4.5-6.1c-.2-.1-1.5-.7-1.7-.8-.2-.1-.4-.1-.6.1l-.8 1c-.1.2-.3.2-.5.1a6.7 6.7 0 0 1-3.3-2.9c-.2-.4.2-.4.7-1.3.1-.2 0-.3 0-.4l-.8-1.8c-.2-.5-.4-.4-.6-.4h-.5a1 1 0 0 0-.7.3 3 3 0 0 0-.9 2.2 5.2 5.2 0 0 0 1.1 2.7 11.8 11.8 0 0 0 4.5 4c1.7.7 2.3.8 3.2.6.5-.1 1.5-.6 1.7-1.2.2-.6.2-1.1.1-1.2l-.4-.2Z"/></svg>' +
          'Send Jay a word</a>' +
      '</footer>' +
    '</div></div>';

  var q = fd$('.fd-q');
  q.addEventListener('input', function () { fdRender(); window.scrollTo({ top: 0, behavior: 'instant' }); });
  fd$('.fd-clear').addEventListener('click', function () { q.value = ''; fdRender(); q.focus(); });
  el.addEventListener('keydown', function (e) {
    if (e.key === 'Escape' && document.activeElement === q && q.value) { q.value = ''; fdRender(); }
  });
  /* one delegated listener: the portal's JS is a closure, so nothing here is inline */
  el.addEventListener('click', function (e) {
    var t = e.target;
    var mode = t.closest('[data-fd-mode]');
    if (mode) { fdSetMode(mode.dataset.fdMode); q.value = ''; fdRender(); window.scrollTo({ top: 0, behavior: 'instant' }); return; }
    var back = t.closest('[data-fd-back]');
    if (back) { if (FD.opts.onBack) FD.opts.onBack(); return; }
    var chip = t.closest('[data-fd-group]');
    // only a day gets its own hash (#dictionary-day-4); letters stay on #dictionary
    if (chip) { e.preventDefault(); var gid = chip.dataset.fdGroup; fdGoTo(gid, false, /^fd-day-\d+$/.test(gid) ? gid.replace(/^fd-/, '') : ''); return; }
    var x = t.closest('.fd-xref[data-fd-to]');
    if (x) {
      e.preventDefault();
      if (q.value.trim() || FD.mode === 'cmd') { q.value = ''; fdSetMode('day'); fdRender(); }
      fdGoTo('fd-t-' + x.dataset.fdTo, true, x.dataset.fdTo);
      return;
    }
    var c = t.closest('[data-fd-copy]');
    if (c) {
      var g = GLOSSARY.filter(function (it) { return it.id === c.dataset.fdCopy; })[0];
      var url = location.origin + location.pathname + '#dictionary-' + c.dataset.fdCopy;
      var ok = fdCopy(url);
      if (FD.opts.toast) FD.opts.toast(ok ? 'Link copied: ' + g.t : url);
    }
  });
  window.addEventListener('scroll', fdStuck, { passive: true });
  window.addEventListener('resize', function () { if (FD.el.offsetParent) { fdMeasure(); fdStuck(); } });
  fdRender();
}

/* show the view: anchor is '' (top), 'day-N' or a term id */
function fdOpen(anchor, backLabel) {
  if (!FD.mounted) return;
  var t = fd$('.fd-back-t');
  if (t) t.textContent = backLabel || 'Back';
  var q = fd$('.fd-q');
  if (q.value || FD.mode !== 'day') { q.value = ''; fdSetMode('day'); fdRender(); }
  fdMeasure();
  fdStuck();
  var done = false;
  if (anchor) {
    if (/^day-\d+$/.test(anchor)) done = fdGoTo('fd-' + anchor, false, anchor);
    else done = fdGoTo('fd-t-' + anchor, true, anchor);
  }
  if (!done) window.scrollTo({ top: 0, behavior: 'instant' });
  fdStuck();
  fdObserve();
  // on a fresh load the portal header grows after this landing (on a phone its day rail
  // wraps to a second row, +35px, and the browser shifts the scroll to hold the view), and
  // web fonts reflow the text. Re-check the real target a few times; stop the moment the
  // reader touches, wheels or keys, never on a scroll the page made by itself (24.9).
  if (done) {
    var id = /^day-\d+$/.test(anchor) ? 'fd-' + anchor : 'fd-t-' + anchor;
    var token = (FD.token = (FD.token || 0) + 1), moved = false;
    var stop = function () { moved = true; };
    ['wheel', 'touchstart', 'keydown', 'mousedown'].forEach(function (ev) { window.addEventListener(ev, stop, { once: true, passive: true }); });
    var check = function () {
      var el = document.getElementById(id);
      if (moved || FD.token !== token || !el || !FD.el.offsetParent) return;
      fdStuck();
      var off = el.getBoundingClientRect().top - (fdHeaderH() + fd$('.fd-toolbar').offsetHeight + 24);
      if (Math.abs(off) > 2) window.scrollBy({ top: off, behavior: 'instant' });
    };
    if (document.fonts && document.fonts.ready) document.fonts.ready.then(check);
    [150, 400, 900, 1800].forEach(function (ms) { setTimeout(check, ms); });
  }
}

window.WonkaDictionary = {
  mount: fdMount,
  open: fdOpen,
  count: function (day) { return GLOSSARY.filter(function (g) { return g.d === day; }).length; },
};

})();
